#! /usr/bin/env bash

set -xe

export $(grep -v '^#' configs/pulumi/${ENV}.env | xargs)

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="$(basename "${BASH_SOURCE[0]}")"
__path="$(echo "${__dir//$PWD}")"

NC='\033[0m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[1;31m'

usage() {
  cat <<EOF

Usage: .$__path/$__file arg1 [arg2...]

Available args:

.$__path/$__file config ENV=dev   update configs, alias: c


EOF
  exit
}

init() {
  ENV=${ENV:-"dev-0"}

  PULUMI_FUNCTION_DIR=${PULUMI_FUNCTION_DIR:-"."}
  PULUMI_PLAN_DIR=${PULUMI_PLAN_DIR:-"."}
  PULUMI_VERSION=$(pulumi version 2>&1 | head -n 1)

  AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-"ap-northeast-1"}


  cat << EOF
Variable Info:
===============================
$(echo -e "${BLUE}ENV:${NC} ${GREEN}${ENV}${NC}")
$(echo -e "${BLUE}ARG:${NC} ${GREEN}${arg1}${NC}")

$(echo -e "${BLUE}PULUMI_DIR:${NC} ${GREEN}${PULUMI_DIR}${NC}")
$(echo -e "${BLUE}PULUMI_VERSION:${NC} ${GREEN}${PULUMI_VERSION}${NC}")

$(echo -e "${BLUE}AWS_DEFAULT_REGION:${NC} ${GREEN}${AWS_DEFAULT_REGION}${NC}")
$(echo -e "${BLUE}AWS_ACCESS_KEY_ID:${NC} ${GREEN}${AWS_ACCESS_KEY_ID}${NC}")
===============================
EOF
}

main() {
  arg1=${1:-usage}

  case $arg1 in
    config|c)
      init
      pulumi stack init $ENV --non-interactive -C $PULUMI_DIR > /dev/null 2>&1 || true
      source ./scripts/config
      ;;
    *)
      init
      usage
      ;;
  esac
}

main $@
